/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Component Pack 6
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <AMux_1.h>
#include <Pin_1_aliases.h>
#include <Pin_1.h>
#include <Pin_2_aliases.h>
#include <Pin_2.h>
#include <Pin_3_aliases.h>
#include <Pin_3.h>
#include <Pin_4_aliases.h>
#include <Pin_4.h>
#include <ADC_SAR_1.h>
#include <LCD_Char_1.h>
#include <Pin_5_aliases.h>
#include <Pin_5.h>
#include <VDAC8_1.h>
#include <Counter_1.h>
#include <Period_1MHz.h>
#include <Control_Reg_1.h>
#include <ADC_SAR_1_IRQ.h>
#include <ADC_SAR_1_theACLK.h>
#include <ADC_SAR_1_Bypass_aliases.h>
#include <ADC_SAR_1_Bypass.h>
#include <LCD_Char_1_LCDPort_aliases.h>
#include <LCD_Char_1_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/

